---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: ENV
          value: "prod"
        - name: ENV_TYPE
          value: "production"
        - name: UI_THEME
          value: "Green"
        #- name: PAGE_LIMIT
        #  value: "25"
        #- name: SORTING
        #  value: "ascending"    
        #- name: N_BUCKETS
        #  value: "42"
        #- name: GPU_ENABLED
        #  value: "1"
        #- name: PAYPAL_URL
        #  value: "production.paypal.com"   
        #- name: DB_USER
        #  value: "prod_username"
        #- name: DB_PASSWORD
        #  value: "prod_password"