name: CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME}}

jobs:

  build:

    runs-on: ubuntu-latest
    
    outputs:
      date: ${{ steps.tagInfo.outputs.date }}
      shaShort: ${{ steps.tagInfo.outputs.shaShort }}    
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Get tag info
      id: tagInfo
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        echo "::set-output name=shaShort::$(git rev-parse --short HEAD)"    
    
    - name: Build the Docker image
      run: docker build -t $DOCKER_USER/$DOCKER_REPO_NAME .

    - name: Login to Docker Hub
      run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Push image to dockerhub
      run: |
        docker tag $DOCKER_USER/$DOCKER_REPO_NAME:latest $DOCKER_USER/$DOCKER_REPO_NAME:${{ steps.tagInfo.outputs.date }}-${{ steps.tagInfo.outputs.shaShort }}
        echo "Push image $DOCKER_USER/$DOCKER_REPO_NAME:${{ steps.tagInfo.outputs.date }}-${{ steps.tagInfo.outputs.shaShort }}"
        docker push $DOCKER_USER/$DOCKER_REPO_NAME:${{ steps.tagInfo.outputs.date }}-${{ steps.tagInfo.outputs.shaShort }}